# Generated by Django 5.1.3 on 2024-11-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_is_paid_member_payment_date_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_paid',
        ),
    ]
